// Reader-facing descriptions are separate from the generated source catalog.
// A catalog refresh must not erase editorial context or change original titles.
export const articleDescriptions: Record<string, string> = {
  "architecting-high-performance-solana": "Explore how zero-copy changes the way a Solana program reads and updates account data.",
  "solana-deep-dive-unpacking-borsh": "Follow structured data into its byte representation, and back again through Borsh.",
  "the-utility-extensions-completing": "A closer look at the utility extensions that round out Token-2022.",
  "native-zk-on-solana-the-architecture": "Look beneath confidential transfers at the architecture that brings zero-knowledge proofs into token operations.",
  "engineering-native-yield-a-deep-dive": "What does an interest-bearing mint actually change? Examine the extension beneath the displayed balance.",
  "transfer-hooks-on-solana-anchor-031": "Work through the connection between Token-2022 transfer hooks and an Anchor program.",
  "solana-token-2022-transfer-hooks": "Explore the mechanics of transfer hooks and transfer fees in the token lifecycle.",
  "from-convention-to-explicit-state": "Trace how a metadata pointer connects a Token-2022 mint to its metadata.",
  "where-token-metadata-lives-on-solana": "Find out where token names, symbols, and other metadata sit in Solana’s account model.",
  "spl-token-program-architecture-a": "Build a mental model of the token program, mints, and token accounts.",
  "understanding-solana-part-6-transactions": "Bring transactions and messages together in practice, including address lookup tables.",
  "understanding-solana-part-5-transaction": "Follow a transaction through serialization, signatures, fees, and runtime execution.",
  "understanding-solana-part4-instructions": "See how individual instructions become the message that a transaction carries.",
  "understanding-solana-part-3-anchor": "Connect Anchor’s account declarations to seeds, bumps, PDAs, and the client that uses them.",
  "understanding-solana-account-model": "Understand what an account contains and how programs work with accounts.",
  "proxies-and-upgradability-minimal": "Examine how a minimal proxy reuses an implementation through delegation.",
  "factories-how-smart-contracts-deploy": "What changes when the thing deploying a smart contract is another smart contract?",
  "proxies-and-upgradability-uups-proxy": "Follow the upgrade mechanism when the implementation holds the upgrade logic.",
  "proxies-and-upgradability": "Explore how a transparent proxy separates administrative operations from user calls.",
  "deployments-and-deterministic-addresses": "Compare how CREATE and CREATE2 determine the address of a new contract.",
  "batching-calls-efficiently-with-multicall": "Compare batching at the contract level with batching requests to an RPC endpoint.",
  "catching-eth-native-transfers-without": "How do you observe native ETH transfers when there is no token Transfer event?",
  "streaming-on-chain-activity-in-real": "Explore the mechanics of following on-chain activity as it happens.",
  "understanding-events-the-evms-built": "Look beneath Solidity events at the EVM’s logs and topics.",
  "eth_call-vs-debug_tracecall-how-to": "Compare a simulated call’s result with a trace of the execution behind it.",
  "whats-behind-your-rpc-node-types": "Understand the node and client behind an endpoint, and why that affects your queries.",
  "evm-message-signtypeddata-eip-712": "Explore structured off-chain signing and the information an EIP-712 signature commits to.",
  "evm-message-signed-data-eip-191-and": "Inspect the Ethereum message prefix and its role in signed data.",
  "evm-tx-setcode-transactions-eip-7702": "Explore EIP-7702 authorization and code delegation for externally owned accounts.",
  "evm-tx-blob-transactions-eip-4844": "Look inside blob transactions and the data-availability problem they address.",
  "evm-tx-dynamic-fee-transactions-eip": "Break down the fee fields and mechanics of an EIP-1559 transaction.",
  "evm-tx-access-list-transactions-eip": "Understand what an access list describes and how it fits into a transaction.",
  "evm-tx-understanding-legacy-ethereum": "Start with the fields and encoding of a legacy Ethereum transaction.",
  "what-is-recursive-length-prefix-rlp": "Work through the rules that turn byte strings and lists into an RLP encoding.",
  "tracing-ethereum-transactions-how": "Read execution step by step instead of stopping at a success or failure status.",
  "evm-developer-tools-explained-foundry": "Get oriented in the EVM toolset and set up Foundry for local exploration.",
  "solidity-execution-overview-payable": "Connect payable functions, fallback behavior, call types, and reverts.",
  "abi-encoding-deep-dive-how-solidity": "See how Solidity values become the bytes used to communicate with contracts.",
  "what-actually-happens-when-calldata": "Follow incoming calldata into the EVM’s execution machinery.",
  "ethereum-calldata-and-bytecode-how": "Trace the connection between a function selector, calldata, and contract bytecode.",
  "introduction-to-the-ethereum-virtual": "An introduction to the execution environment beneath Ethereum smart contracts.",
  "understanding-solana-architecture-account-model-and-transactions-part-1-1bffae449650": "Start with Solana’s architecture before getting into accounts, programs, and transactions.",
  "diamonds-in-evm-the-proxy-that-scales-beyond-limits-2fedc282cadf": "Explore a proxy architecture that routes calls across multiple implementation facets.",
  "understanding-contract-deployments-proxies-and-create2-part-2-df8f05998d5e": "Continue the deployment series into proxies and contract architecture.",
  "understanding-contract-deployments-proxies-and-create2-part-1-696b0b11f8a5": "Start tracing how contracts are created and how their deployment addresses are determined.",
  "ethereum-dev-hacks-catching-hidden-transfers-real-time-events-and-multicalls-bef7435b9397": "Connect transfer detection, live events, and batched calls in Ethereum tooling.",
  "ethereum-node-types-explained-and-why-they-can-make-or-break-your-debugging-fc8d89b724cc": "Understand how the node you query shapes the information available for debugging.",
  "gas-matters-how-to-reduce-transaction-costs-in-your-solidity-code-0c0303d61a4f": "Examine where Solidity execution spends gas and how to approach reducing it.",
  "understanding-ethereum-transactions-and-messages-from-state-changes-to-off-chain-messages-part-2-e8ef96b82768": "Continue from on-chain transactions into the role of off-chain messages.",
  "understanding-ethereum-transactions-and-messages-from-state-changes-to-off-chain-messages-part-1-54130865e71e": "Start separating transactions that change chain state from messages signed off chain.",
  "what-every-blockchain-developer-should-know-about-evm-internals-part-3-b6813d964592": "The third part of the original EVM internals series, continuing below Solidity’s abstractions.",
  "what-every-blockchain-developer-should-know-about-evm-internals-part-2-eab0f4fae3de": "Continue the original EVM internals series with a closer look at contract execution.",
  "what-every-blockchain-developer-should-know-about-evm-internals-part-1-83a93c618257": "What is the EVM actually executing? Start with gas, bytecode, and the places a contract keeps its data.",
  "hyperliquid-beyond-generic-vms-the": "Why split a blockchain into HyperCore and HyperEVM? Start with the architecture behind the exchange.",
};

export const articlesWithoutCode = new Set([
  "understanding-solana-architecture-account-model-and-transactions-part-1-1bffae449650",
]);
